/* axis: 'g' whole/fresh · 'a' mid · 'r' processed/intense */

export type Axis = 'g' | 'a' | 'r'

export type Match = {
  name: string
  pct:  number
  axis: Axis
  why:  string
  note: string
}

export type Seed = {
  label:     string
  classic:    Match[]
  surprising: Match[]
}

export type SeedChip = { key: string; axis: Axis }

// Real Epicure data generated by scripts/build_flavors.py
import generated from './flavors.generated.json'

const gen = generated as {
  flavors:    Record<string, Seed>
  seed_chips: SeedChip[]
}

export const FLAVORS: Record<string, Seed> = gen.flavors
export const SEED_CHIPS: SeedChip[]        = gen.seed_chips

// Kept for constrained search fallback — Phase 2 /api/search supersedes these
export const STAPLE_ALIASES: Record<string, string[]> = {
  fig:        ['figs', 'black mission fig', 'dried fig', 'date', 'prune'],
  coffee:     ['espresso', 'latte', 'cold brew', 'mocha', 'cacao', 'cocoa', 'dark chocolate'],
  strawberry: ['strawberries', 'wild strawberry', 'raspberry', 'cherry', 'blackberry'],
  basil:      ['sweet basil', 'thai basil', 'genovese basil', 'holy basil', 'mint', 'oregano'],
  miso:       ['white miso', 'red miso', 'shiro miso', 'soy sauce', 'sea salt', 'maldon flakes', 'salt'],
}

export const NO_MATCH_TERMS: string[] = ['durian', 'natto', 'century egg', 'vegemite', 'marmite']

export const FLAVOR_EDGE = {
  noMatch: {
    label: 'Durian',
    cousins: [
      { name: 'Jackfruit',    axis: 'g' as Axis },
      { name: 'Mango',        axis: 'g' as Axis },
      { name: 'Shrimp paste', axis: 'r' as Axis },
    ],
  },
  oov: { typed: 'maldon flakes', mapped: 'Sea salt', axis: 'r' as Axis },
}
