#!/usr/bin/env python3
"""Patch why/note editorial copy into flavors.generated.json (no API needed)."""
import json, os

HERE = os.path.dirname(__file__)
PATH = os.path.join(HERE, "../shared/flavors.generated.json")

# (lens, seed, partner_display_name) → (why, note)
COPY: dict[tuple, tuple] = {
# ── fig ──────────────────────────────────────────────────────────────────────
("classic","fig","Apricot"):          ("paired in ~1,800 recipes · stone-fruit kin",   "~1,800 recipes"),
("classic","fig","Pear"):             ("paired in ~250 recipes · soft autumn sweet",    "~250 recipes"),
("classic","fig","Edible Flower"):    ("paired in ~250 recipes · floral elegance",      "~250 recipes"),
("classic","fig","Hazelnut"):         ("paired in ~250 recipes · rich nuttiness",       "~250 recipes"),
("classic","fig","Quinoa"):           ("paired in ~250 recipes · grain contrast",       "~250 recipes"),
("classic","fig","Date"):             ("paired in ~250 recipes · honeyed depth",        "~250 recipes"),
("surprising","fig","Date"):              ("shares ~12 aroma compounds · honeyed fruit",    "~12 compounds"),
("surprising","fig","Bitter Almond"):     ("shares ~8 aroma compounds · floral nuttiness",  "~8 compounds"),
("surprising","fig","Sea Coconut"):       ("shares ~8 aroma compounds · tropical sweet",    "~8 compounds"),
("surprising","fig","Red Date"):          ("shares ~5 aroma compounds · caramel fruit",     "~5 compounds"),
("surprising","fig","Longan"):            ("shares ~5 aroma compounds · floral honey",      "~5 compounds"),
("surprising","fig","Tiger Milk Mushroom"):("shares ~5 aroma compounds · earthy sweet",    "~5 compounds"),
# ── coffee ───────────────────────────────────────────────────────────────────
("classic","coffee","Cocoa Powder"):      ("paired in ~1,800 recipes · roasty depth",      "~1,800 recipes"),
("classic","coffee","Chocolate"):         ("paired in ~700 recipes · bitter kin",          "~700 recipes"),
("classic","coffee","Rum"):              ("paired in ~700 recipes · dark warmth",          "~700 recipes"),
("classic","coffee","Coffee Liqueur"):    ("paired in ~700 recipes · double roast",        "~700 recipes"),
("classic","coffee","Vanilla"):           ("paired in ~700 recipes · cream balance",       "~700 recipes"),
("classic","coffee","Cacao"):             ("paired in ~250 recipes · raw bitter",          "~250 recipes"),
("surprising","coffee","Coffee Liqueur"):  ("shares ~12 aroma compounds · caramel pyrazine","~12 compounds"),
("surprising","coffee","Chocolate"):       ("shares ~5 aroma compounds · roasty overlap",  "~5 compounds"),
("surprising","coffee","Irish Cream"):     ("shares ~5 aroma compounds · creamy bitter",   "~5 compounds"),
("surprising","coffee","Cacao"):           ("shares ~5 aroma compounds · raw roast",       "~5 compounds"),
("surprising","coffee","Chocolate Liqueur"):("shares ~5 aroma compounds · sweet dark",    "~5 compounds"),
("surprising","coffee","Ladyfinger"):      ("shares ~5 aroma compounds · soaked sponge",  "~5 compounds"),
# ── strawberry ───────────────────────────────────────────────────────────────
("classic","strawberry","Raspberry"):     ("paired in ~1,800 recipes · berry twins",       "~1,800 recipes"),
("classic","strawberry","Blueberry"):     ("paired in ~250 recipes · mixed berry",         "~250 recipes"),
("classic","strawberry","Ice Cream"):     ("paired in ~250 recipes · cold sweet",          "~250 recipes"),
("classic","strawberry","Banana"):        ("paired in ~250 recipes · tropical blend",      "~250 recipes"),
("classic","strawberry","Blackberry"):    ("paired in ~250 recipes · dark berry lift",     "~250 recipes"),
("classic","strawberry","Rum"):           ("paired in ~250 recipes · boozy sweet",         "~250 recipes"),
("surprising","strawberry","Cream"):       ("shares ~12 aroma compounds · ester overlap",  "~12 compounds"),
("surprising","strawberry","Gelatin"):     ("shares ~8 aroma compounds · set dessert",     "~8 compounds"),
("surprising","strawberry","Peach"):       ("shares ~8 aroma compounds · summer stone",    "~8 compounds"),
("surprising","strawberry","Apple"):       ("shares ~5 aroma compounds · shared esters",   "~5 compounds"),
("surprising","strawberry","Raspberry"):   ("shares ~5 aroma compounds · berry aldehydes", "~5 compounds"),
("surprising","strawberry","Pineapple"):   ("shares ~5 aroma compounds · tropical ester",  "~5 compounds"),
# ── basil ────────────────────────────────────────────────────────────────────
("classic","basil","Parsley"):            ("paired in ~1,800 recipes · herb duo",          "~1,800 recipes"),
("classic","basil","Olive Oil"):          ("paired in ~700 recipes · Mediterranean base",  "~700 recipes"),
("classic","basil","Parmesan Cheese"):    ("paired in ~700 recipes · Italian classic",     "~700 recipes"),
("classic","basil","Black Pepper"):       ("paired in ~700 recipes · pungent lift",        "~700 recipes"),
("classic","basil","White Wine"):         ("paired in ~250 recipes · bright acid",         "~250 recipes"),
("classic","basil","Thyme"):              ("paired in ~250 recipes · herb accord",         "~250 recipes"),
("surprising","basil","Tarragon"):         ("shares ~12 aroma compounds · anise kin",       "~12 compounds"),
("surprising","basil","Oregano"):          ("shares ~12 aroma compounds · Mediterranean overlap","~12 compounds"),
("surprising","basil","Rosemary"):         ("shares ~8 aroma compounds · terpene family",  "~8 compounds"),
("surprising","basil","Pasta"):            ("shares ~5 aroma compounds · pesto target",    "~5 compounds"),
("surprising","basil","Fennel"):           ("shares ~5 aroma compounds · anise overlap",   "~5 compounds"),
("surprising","basil","Zucchini"):         ("shares ~5 aroma compounds · summer green",    "~5 compounds"),
# ── miso ─────────────────────────────────────────────────────────────────────
("classic","miso","Sake"):               ("paired in ~1,800 recipes · fermented grain",   "~1,800 recipes"),
("classic","miso","Snow Pea"):           ("paired in ~700 recipes · spring fresh",        "~700 recipes"),
("classic","miso","Mirin"):              ("paired in ~700 recipes · sweet umami",         "~700 recipes"),
("classic","miso","Shichimi Togarashi"): ("paired in ~250 recipes · heat contrast",       "~250 recipes"),
("classic","miso","Fried Tofu Puff"):    ("paired in ~250 recipes · sponge umami",        "~250 recipes"),
("classic","miso","Bonito Flakes"):      ("paired in ~250 recipes · dashi depth",         "~250 recipes"),
("surprising","miso","Octopus"):           ("shares ~12 aroma compounds · sea umami",      "~12 compounds"),
("surprising","miso","Kombu"):             ("shares ~12 aroma compounds · glutamate stack","~12 compounds"),
("surprising","miso","Natto"):             ("shares ~8 aroma compounds · fermented deep",  "~8 compounds"),
("surprising","miso","Tofu"):              ("shares ~8 aroma compounds · soy kin",         "~8 compounds"),
("surprising","miso","Wakame"):            ("shares ~5 aroma compounds · marine soft",     "~5 compounds"),
("surprising","miso","Soy Milk"):          ("shares ~5 aroma compounds · soy core",        "~5 compounds"),
# ── garlic ───────────────────────────────────────────────────────────────────
("classic","garlic","Chili Pepper"):      ("paired in ~1,800 recipes · heat anchor",      "~1,800 recipes"),
("classic","garlic","Salt"):              ("paired in ~700 recipes · seasoning base",      "~700 recipes"),
("classic","garlic","Tomato"):            ("paired in ~250 recipes · sofrito start",       "~250 recipes"),
("classic","garlic","Onion"):             ("paired in ~250 recipes · aromatic twin",       "~250 recipes"),
("classic","garlic","Oil"):               ("paired in ~250 recipes · infused base",        "~250 recipes"),
("classic","garlic","Black Pepper"):      ("paired in ~250 recipes · pungent accord",      "~250 recipes"),
("surprising","garlic","Chive"):           ("shares ~12 aroma compounds · allium family",  "~12 compounds"),
("surprising","garlic","Shallot"):         ("shares ~12 aroma compounds · allium kin",     "~12 compounds"),
("surprising","garlic","Onion"):           ("shares ~8 aroma compounds · thiosulfinate bond","~8 compounds"),
("surprising","garlic","Leek"):            ("shares ~8 aroma compounds · sulfur allium",   "~8 compounds"),
("surprising","garlic","Scallion"):        ("shares ~5 aroma compounds · sharp green",     "~5 compounds"),
("surprising","garlic","Shiitake Mushroom"):("shares ~5 aroma compounds · earthy sulfur",  "~5 compounds"),
# ── ginger ───────────────────────────────────────────────────────────────────
("classic","ginger","Light Soy Sauce"):   ("paired in ~1,800 recipes · East Asian base",  "~1,800 recipes"),
("classic","ginger","Soy Sauce"):         ("paired in ~700 recipes · umami heat",         "~700 recipes"),
("classic","ginger","Sesame Oil"):        ("paired in ~700 recipes · toasted warmth",     "~700 recipes"),
("classic","ginger","Msg"):               ("paired in ~250 recipes · umami boost",        "~250 recipes"),
("classic","ginger","Birds Eye Chili"):   ("paired in ~250 recipes · heat stack",         "~250 recipes"),
("classic","ginger","Sichuan Peppercorn"):("paired in ~250 recipes · numbing spice",      "~250 recipes"),
("surprising","ginger","Scallion"):        ("shares ~12 aroma compounds · zingy green",    "~12 compounds"),
("surprising","ginger","Shaoxing Wine"):   ("shares ~12 aroma compounds · fermented warmth","~12 compounds"),
("surprising","ginger","Star Anise"):      ("shares ~8 aroma compounds · spice bridge",   "~8 compounds"),
("surprising","ginger","Ginkgo Nut"):      ("shares ~5 aroma compounds · bitter resin",   "~5 compounds"),
("surprising","ginger","Tofu"):            ("shares ~5 aroma compounds · mild canvas",    "~5 compounds"),
("surprising","ginger","Sichuan Peppercorn"):("shares ~5 aroma compounds · numbing citrus","~5 compounds"),
# ── onion ────────────────────────────────────────────────────────────────────
("classic","onion","Tomato"):             ("paired in ~1,800 recipes · sofrito soul",     "~1,800 recipes"),
("classic","onion","Paprika"):            ("paired in ~700 recipes · sweet heat",         "~700 recipes"),
("classic","onion","Garlic"):             ("paired in ~700 recipes · aromatic base",      "~700 recipes"),
("classic","onion","Parsley"):            ("paired in ~250 recipes · herb finish",        "~250 recipes"),
("classic","onion","Black Pepper"):       ("paired in ~250 recipes · spice layer",        "~250 recipes"),
("classic","onion","Thyme"):              ("paired in ~250 recipes · slow simmer",        "~250 recipes"),
("surprising","onion","Garlic"):           ("shares ~12 aroma compounds · allium twins",   "~12 compounds"),
("surprising","onion","Chive"):            ("shares ~12 aroma compounds · thiosulfinate kin","~12 compounds"),
("surprising","onion","Leek"):             ("shares ~8 aroma compounds · sweet allium",   "~8 compounds"),
("surprising","onion","Shallot"):          ("shares ~8 aroma compounds · delicate allium","~8 compounds"),
("surprising","onion","Zucchini"):         ("shares ~5 aroma compounds · summer vegetal", "~5 compounds"),
("surprising","onion","Bell Pepper"):      ("shares ~5 aroma compounds · sweet vegetal",  "~5 compounds"),
# ── lemon ────────────────────────────────────────────────────────────────────
("classic","lemon","Orange"):             ("paired in ~1,800 recipes · citrus kin",       "~1,800 recipes"),
("classic","lemon","Mint"):               ("paired in ~700 recipes · bright fresh",       "~700 recipes"),
("classic","lemon","Rosemary"):           ("paired in ~700 recipes · herb lift",          "~700 recipes"),
("classic","lemon","Cherry"):             ("paired in ~700 recipes · tart fruit",         "~700 recipes"),
("classic","lemon","Mustard"):            ("paired in ~250 recipes · sharp acid",         "~250 recipes"),
("classic","lemon","White Wine"):         ("paired in ~250 recipes · acid mirror",        "~250 recipes"),
("surprising","lemon","Lime"):             ("shares ~12 aroma compounds · limonene twins", "~12 compounds"),
("surprising","lemon","Clementine"):       ("shares ~8 aroma compounds · citral kin",     "~8 compounds"),
("surprising","lemon","Orange"):           ("shares ~8 aroma compounds · citrus terpene", "~8 compounds"),
("surprising","lemon","Pomegranate"):      ("shares ~5 aroma compounds · tart overlap",   "~5 compounds"),
("surprising","lemon","Parsley"):          ("shares ~5 aroma compounds · green citrus",   "~5 compounds"),
("surprising","lemon","Cardamom"):         ("shares ~5 aroma compounds · citrus spice",   "~5 compounds"),
# ── tomato ───────────────────────────────────────────────────────────────────
("classic","tomato","Onion"):             ("paired in ~1,800 recipes · sauce foundation", "~1,800 recipes"),
("classic","tomato","Parsley"):           ("paired in ~700 recipes · green brightness",   "~700 recipes"),
("classic","tomato","Garlic"):            ("paired in ~700 recipes · Italian holy trio",  "~700 recipes"),
("classic","tomato","Olive Oil"):         ("paired in ~700 recipes · Mediterranean pull", "~700 recipes"),
("classic","tomato","Bell Pepper"):       ("paired in ~250 recipes · sweet vegetal",      "~250 recipes"),
("classic","tomato","Black Pepper"):      ("paired in ~250 recipes · sharp seasoning",    "~250 recipes"),
("surprising","tomato","Bean"):            ("shares ~12 aroma compounds · green vegetal",  "~12 compounds"),
("surprising","tomato","Bell Pepper"):     ("shares ~12 aroma compounds · pyrazine family","~12 compounds"),
("surprising","tomato","Red Pepper"):      ("shares ~8 aroma compounds · carotenoid kin", "~8 compounds"),
("surprising","tomato","Tortilla"):        ("shares ~8 aroma compounds · corn sweet",     "~8 compounds"),
("surprising","tomato","Onion"):           ("shares ~5 aroma compounds · sulfur vegetal", "~5 compounds"),
("surprising","tomato","Kidney Bean"):     ("shares ~5 aroma compounds · legume green",   "~5 compounds"),
# ── mushroom ─────────────────────────────────────────────────────────────────
("classic","mushroom","Olive Oil"):       ("paired in ~1,800 recipes · sauté base",       "~1,800 recipes"),
("classic","mushroom","Chive"):           ("paired in ~700 recipes · mild onion lift",    "~700 recipes"),
("classic","mushroom","Italian Seasoning"):("paired in ~700 recipes · herb blend",        "~700 recipes"),
("classic","mushroom","Black Pepper"):    ("paired in ~700 recipes · earthy heat",        "~700 recipes"),
("classic","mushroom","Carrot"):          ("paired in ~700 recipes · root duo",           "~700 recipes"),
("classic","mushroom","Onion"):           ("paired in ~250 recipes · aromatic start",     "~250 recipes"),
("surprising","mushroom","Pasta"):         ("shares ~12 aroma compounds · carbonyl match", "~12 compounds"),
("surprising","mushroom","Swiss Cheese"):  ("shares ~12 aroma compounds · umami overlap",  "~12 compounds"),
("surprising","mushroom","Zucchini"):      ("shares ~5 aroma compounds · vegetal earthy",  "~5 compounds"),
("surprising","mushroom","Egg Noodle"):    ("shares ~5 aroma compounds · wheat earthy",    "~5 compounds"),
("surprising","mushroom","Bread"):         ("shares ~5 aroma compounds · yeast umami",     "~5 compounds"),
("surprising","mushroom","Beef"):          ("shares ~5 aroma compounds · savory depth",    "~5 compounds"),
# ── avocado ──────────────────────────────────────────────────────────────────
("classic","avocado","Lettuce"):          ("paired in ~1,800 recipes · salad anchor",     "~1,800 recipes"),
("classic","avocado","Arugula"):          ("paired in ~250 recipes · peppery green",      "~250 recipes"),
("classic","avocado","Bread"):            ("paired in ~250 recipes · toast canvas",       "~250 recipes"),
("classic","avocado","Black Pepper"):     ("paired in ~250 recipes · sharp contrast",     "~250 recipes"),
("classic","avocado","Monterey Jack Cheese"):("paired in ~250 recipes · creamy melt",    "~250 recipes"),
("classic","avocado","Salmon"):           ("paired in ~250 recipes · fat on fat",         "~250 recipes"),
("surprising","avocado","Tortilla"):       ("shares ~12 aroma compounds · Mesoamerican kin","~12 compounds"),
("surprising","avocado","Quinoa"):         ("shares ~8 aroma compounds · South American pair","~8 compounds"),
("surprising","avocado","Tomatillo"):      ("shares ~8 aroma compounds · green vegetal",  "~8 compounds"),
("surprising","avocado","Jicama"):         ("shares ~5 aroma compounds · crisp fresh",    "~5 compounds"),
("surprising","avocado","Nopal"):          ("shares ~5 aroma compounds · Mexican trio",   "~5 compounds"),
("surprising","avocado","Epazote"):        ("shares ~5 aroma compounds · herbal green",   "~5 compounds"),
# ── carrot ───────────────────────────────────────────────────────────────────
("classic","carrot","Pea"):              ("paired in ~1,800 recipes · garden pair",       "~1,800 recipes"),
("classic","carrot","Cabbage"):          ("paired in ~250 recipes · slaw classic",        "~250 recipes"),
("classic","carrot","Sesame Oil"):       ("paired in ~250 recipes · East Asian roast",    "~250 recipes"),
("classic","carrot","Mushroom"):         ("paired in ~250 recipes · earthy root",         "~250 recipes"),
("classic","carrot","Chicken"):          ("paired in ~250 recipes · braise base",         "~250 recipes"),
("classic","carrot","Rice"):             ("paired in ~250 recipes · pilaf balance",       "~250 recipes"),
("surprising","carrot","Pea"):             ("shares ~12 aroma compounds · pyrazine twins", "~12 compounds"),
("surprising","carrot","Celery"):          ("shares ~8 aroma compounds · root vegetal",   "~8 compounds"),
("surprising","carrot","Zucchini"):        ("shares ~8 aroma compounds · summer vegetal", "~8 compounds"),
("surprising","carrot","Nori"):            ("shares ~5 aroma compounds · sweet marine",   "~5 compounds"),
("surprising","carrot","Parsnip"):         ("shares ~5 aroma compounds · root family",    "~5 compounds"),
("surprising","carrot","Bok Choy"):        ("shares ~5 aroma compounds · Asian green",    "~5 compounds"),
# ── spinach ──────────────────────────────────────────────────────────────────
("classic","spinach","Black Pepper"):    ("paired in ~1,800 recipes · wilted seasoning",  "~1,800 recipes"),
("classic","spinach","Olive Oil"):       ("paired in ~700 recipes · sauté standard",      "~700 recipes"),
("classic","spinach","Parsley"):         ("paired in ~250 recipes · green duet",          "~250 recipes"),
("classic","spinach","Salad Greens"):    ("paired in ~250 recipes · leaf blend",          "~250 recipes"),
("classic","spinach","Goat Cheese"):     ("paired in ~250 recipes · tangy cream",         "~250 recipes"),
("classic","spinach","Cabbage"):         ("paired in ~250 recipes · brassica kin",        "~250 recipes"),
("surprising","spinach","Swiss Chard"):    ("shares ~12 aroma compounds · leafy green kin","~12 compounds"),
("surprising","spinach","Zucchini"):       ("shares ~12 aroma compounds · chlorophyll overlap","~12 compounds"),
("surprising","spinach","Pasta"):          ("shares ~8 aroma compounds · green sauce",    "~8 compounds"),
("surprising","spinach","Canola Oil"):     ("shares ~8 aroma compounds · neutral fat",    "~8 compounds"),
("surprising","spinach","Ricotta Cheese"): ("shares ~5 aroma compounds · mild dairy",    "~5 compounds"),
("surprising","spinach","Kale"):           ("shares ~5 aroma compounds · bitter green",  "~5 compounds"),
# ── chicken ──────────────────────────────────────────────────────────────────
("classic","chicken","Garlic"):          ("paired in ~1,800 recipes · universal base",    "~1,800 recipes"),
("classic","chicken","Onion"):           ("paired in ~700 recipes · roast anchor",        "~700 recipes"),
("classic","chicken","Black Pepper"):    ("paired in ~700 recipes · seasoning backbone",  "~700 recipes"),
("classic","chicken","Turkey"):          ("paired in ~250 recipes · poultry kin",         "~250 recipes"),
("classic","chicken","Carrot"):          ("paired in ~250 recipes · braise comfort",      "~250 recipes"),
("classic","chicken","Chicken Broth"):   ("paired in ~250 recipes · stock deepen",        "~250 recipes"),
("surprising","chicken","Beef"):           ("shares ~12 aroma compounds · Maillard cousins","~12 compounds"),
("surprising","chicken","Pork"):           ("shares ~8 aroma compounds · roast amino",    "~8 compounds"),
("surprising","chicken","Cream Of Chicken Soup"):("shares ~8 aroma compounds · cooked poultry","~8 compounds"),
("surprising","chicken","Buffalo Wing Sauce"):("shares ~5 aroma compounds · acetic heat","~5 compounds"),
("surprising","chicken","Peanut"):         ("shares ~5 aroma compounds · satay amino",   "~5 compounds"),
("surprising","chicken","Shrimp"):         ("shares ~5 aroma compounds · Maillard marine","~5 compounds"),
# ── salmon ───────────────────────────────────────────────────────────────────
("classic","salmon","Wasabi"):           ("paired in ~1,800 recipes · sushi icon",        "~1,800 recipes"),
("classic","salmon","Avocado"):          ("paired in ~250 recipes · omega pairing",       "~250 recipes"),
("classic","salmon","Ponzu"):            ("paired in ~250 recipes · citrus umami",        "~250 recipes"),
("classic","salmon","Balsamic Vinegar"): ("paired in ~250 recipes · acid glaze",          "~250 recipes"),
("classic","salmon","Scallop"):          ("paired in ~250 recipes · seafood duo",         "~250 recipes"),
("classic","salmon","Fish Roe"):         ("paired in ~250 recipes · ocean luxury",        "~250 recipes"),
("surprising","salmon","Ham"):             ("shares ~12 aroma compounds · cured protein",  "~12 compounds"),
("surprising","salmon","Trout"):           ("shares ~5 aroma compounds · freshwater kin", "~5 compounds"),
("surprising","salmon","Tuna"):            ("shares ~5 aroma compounds · omega fatty",    "~5 compounds"),
("surprising","salmon","Cod"):             ("shares ~5 aroma compounds · white fish",     "~5 compounds"),
("surprising","salmon","Miso"):            ("shares ~5 aroma compounds · fermented umami","~5 compounds"),
("surprising","salmon","Wasabi"):          ("shares ~5 aroma compounds · isothiocyanate", "~5 compounds"),
# ── egg ──────────────────────────────────────────────────────────────────────
("classic","egg","Flour"):               ("paired in ~1,800 recipes · baking bond",       "~1,800 recipes"),
("classic","egg","Egg Yolk"):            ("paired in ~700 recipes · double yolk",         "~700 recipes"),
("classic","egg","Milk"):                ("paired in ~700 recipes · dairy trio",          "~700 recipes"),
("classic","egg","Baking Powder"):       ("paired in ~700 recipes · lift agent",          "~700 recipes"),
("classic","egg","Vanilla"):             ("paired in ~250 recipes · custard base",        "~250 recipes"),
("classic","egg","Condensed Milk"):      ("paired in ~250 recipes · sweet dense",         "~250 recipes"),
("surprising","egg","Baking Powder"):      ("shares ~12 aroma compounds · leavening pair","~12 compounds"),
("surprising","egg","Baking Soda"):        ("shares ~8 aroma compounds · alkaline lift",  "~8 compounds"),
("surprising","egg","Egg Yolk"):           ("shares ~8 aroma compounds · lecithin kin",   "~8 compounds"),
("surprising","egg","Brown Sugar"):        ("shares ~5 aroma compounds · Maillard sweet", "~5 compounds"),
("surprising","egg","Vegetable Oil"):      ("shares ~5 aroma compounds · fat emulsify",   "~5 compounds"),
("surprising","egg","Graham Flour"):       ("shares ~5 aroma compounds · whole wheat",    "~5 compounds"),
# ── butter ───────────────────────────────────────────────────────────────────
("classic","butter","Cream"):            ("paired in ~1,800 recipes · dairy duo",         "~1,800 recipes"),
("classic","butter","Egg Yolk"):         ("paired in ~700 recipes · hollandaise base",    "~700 recipes"),
("classic","butter","Flour"):            ("paired in ~700 recipes · roux foundation",     "~700 recipes"),
("classic","butter","Milk"):             ("paired in ~700 recipes · beurre blanc",        "~700 recipes"),
("classic","butter","Almond"):           ("paired in ~250 recipes · frangipane",          "~250 recipes"),
("classic","butter","Thyme"):            ("paired in ~250 recipes · basted warmth",       "~250 recipes"),
("surprising","butter","Milk"):            ("shares ~12 aroma compounds · dairy fat",      "~12 compounds"),
("surprising","butter","Flour"):           ("shares ~5 aroma compounds · baked crust",    "~5 compounds"),
("surprising","butter","Egg"):             ("shares ~5 aroma compounds · emulsion kin",   "~5 compounds"),
("surprising","butter","Chocolate"):       ("shares ~5 aroma compounds · ganache base",   "~5 compounds"),
("surprising","butter","Parmesan Cheese"): ("shares ~5 aroma compounds · fat depth",      "~5 compounds"),
("surprising","butter","Pastry"):          ("shares ~5 aroma compounds · flaky matrix",   "~5 compounds"),
# ── cream ────────────────────────────────────────────────────────────────────
("classic","cream","Butter"):            ("paired in ~1,800 recipes · dairy soul",        "~1,800 recipes"),
("classic","cream","Egg Yolk"):          ("paired in ~700 recipes · crème brûlée",        "~700 recipes"),
("classic","cream","Gelatin"):           ("paired in ~250 recipes · panna cotta",         "~250 recipes"),
("classic","cream","Ice Cream"):         ("paired in ~250 recipes · frozen rich",         "~250 recipes"),
("classic","cream","Brandy"):            ("paired in ~250 recipes · flambé base",         "~250 recipes"),
("classic","cream","Cookie"):            ("paired in ~250 recipes · cream filling",       "~250 recipes"),
("surprising","cream","Gelatin"):          ("shares ~12 aroma compounds · set texture",    "~12 compounds"),
("surprising","cream","Chocolate"):        ("shares ~8 aroma compounds · ganache overlap", "~8 compounds"),
("surprising","cream","Meringue"):         ("shares ~8 aroma compounds · sweet fat",       "~8 compounds"),
("surprising","cream","Ice Cream"):        ("shares ~8 aroma compounds · dairy frozen",    "~8 compounds"),
("surprising","cream","Cocoa Powder"):     ("shares ~5 aroma compounds · dark fat",        "~5 compounds"),
("surprising","cream","Sugar"):            ("shares ~5 aroma compounds · sweet dairy",     "~5 compounds"),
# ── cheese ───────────────────────────────────────────────────────────────────
("classic","cheese","Mozzarella Cheese"): ("paired in ~1,800 recipes · Italian stretchy", "~1,800 recipes"),
("classic","cheese","Mayonnaise"):        ("paired in ~700 recipes · creamy blend",        "~700 recipes"),
("classic","cheese","Onion"):             ("paired in ~700 recipes · savory base",         "~700 recipes"),
("classic","cheese","Black Pepper"):      ("paired in ~700 recipes · sharp contrast",      "~700 recipes"),
("classic","cheese","Olive Oil"):         ("paired in ~250 recipes · Mediterranean drizzle","~250 recipes"),
("classic","cheese","Mushroom"):          ("paired in ~250 recipes · earthy umami",        "~250 recipes"),
("surprising","cheese","Mozzarella Cheese"): ("shares ~12 aroma compounds · milk protein", "~12 compounds"),
("surprising","cheese","Muenster Cheese"):   ("shares ~12 aroma compounds · washed rind",  "~12 compounds"),
("surprising","cheese","Cheddar Cheese"):    ("shares ~8 aroma compounds · aged fat",      "~8 compounds"),
("surprising","cheese","Cottage Cheese"):    ("shares ~8 aroma compounds · fresh curd",    "~8 compounds"),
("surprising","cheese","Feta Cheese"):       ("shares ~5 aroma compounds · brined tang",   "~5 compounds"),
("surprising","cheese","Goat Cheese"):       ("shares ~5 aroma compounds · capric acid",   "~5 compounds"),
# ── olive_oil ────────────────────────────────────────────────────────────────
("classic","olive_oil","Parsley"):        ("paired in ~1,800 recipes · gremolata base",   "~1,800 recipes"),
("classic","olive_oil","Tomato"):         ("paired in ~700 recipes · bruschetta soul",    "~700 recipes"),
("classic","olive_oil","Arugula"):        ("paired in ~700 recipes · peppery salad",      "~700 recipes"),
("classic","olive_oil","Basil"):          ("paired in ~700 recipes · pesto heart",        "~700 recipes"),
("classic","olive_oil","Bread"):          ("paired in ~250 recipes · dipping classic",    "~250 recipes"),
("classic","olive_oil","Caper"):          ("paired in ~250 recipes · briny punch",        "~250 recipes"),
("surprising","olive_oil","Red Onion"):    ("shares ~12 aroma compounds · vegetal aldehydes","~12 compounds"),
("surprising","olive_oil","Balsamic Vinegar"):("shares ~12 aroma compounds · polyphenol pair","~12 compounds"),
("surprising","olive_oil","Red Wine Vinegar"):("shares ~8 aroma compounds · acid kin",   "~8 compounds"),
("surprising","olive_oil","Cayenne Pepper"):  ("shares ~5 aroma compounds · fat-soluble heat","~5 compounds"),
("surprising","olive_oil","White Wine Vinegar"):("shares ~5 aroma compounds · bright acid","~5 compounds"),
("surprising","olive_oil","Sherry Vinegar"):  ("shares ~5 aroma compounds · oxidative depth","~5 compounds"),
# ── honey ────────────────────────────────────────────────────────────────────
("classic","honey","Apple"):              ("paired in ~1,800 recipes · orchard sweet",    "~1,800 recipes"),
("classic","honey","Gelatin"):            ("paired in ~250 recipes · jelly preserve",     "~250 recipes"),
("classic","honey","Blueberry"):          ("paired in ~250 recipes · wild sweet",         "~250 recipes"),
("classic","honey","Cherry"):             ("paired in ~250 recipes · stone-fruit glaze",  "~250 recipes"),
("classic","honey","Vanilla"):            ("paired in ~250 recipes · blossom warmth",     "~250 recipes"),
("classic","honey","Cinnamon"):           ("paired in ~250 recipes · spiced drizzle",     "~250 recipes"),
("surprising","honey","Pear"):             ("shares ~12 aroma compounds · floral ester",   "~12 compounds"),
("surprising","honey","Apple"):            ("shares ~8 aroma compounds · fruity ester",   "~8 compounds"),
("surprising","honey","Strawberry"):       ("shares ~8 aroma compounds · sweet overlap",  "~8 compounds"),
("surprising","honey","Char Siu Sauce"):   ("shares ~5 aroma compounds · lacquered sweet","~5 compounds"),
("surprising","honey","Wisteria Flower"):  ("shares ~5 aroma compounds · floral compound","~5 compounds"),
("surprising","honey","Vinegar"):          ("shares ~5 aroma compounds · acetic balance", "~5 compounds"),
# ── soy_sauce ────────────────────────────────────────────────────────────────
("classic","soy_sauce","Sesame Oil"):     ("paired in ~1,800 recipes · East Asian base",  "~1,800 recipes"),
("classic","soy_sauce","Shiitake Mushroom"):("paired in ~250 recipes · umami stack",      "~250 recipes"),
("classic","soy_sauce","Ginger"):         ("paired in ~250 recipes · ginger-soy duo",    "~250 recipes"),
("classic","soy_sauce","Oyster Sauce"):   ("paired in ~250 recipes · double umami",       "~250 recipes"),
("classic","soy_sauce","Light Soy Sauce"):("paired in ~250 recipes · layered salt",      "~250 recipes"),
("classic","soy_sauce","Shaoxing Wine"):  ("paired in ~250 recipes · Chinese trinity",    "~250 recipes"),
("surprising","soy_sauce","Scallion"):     ("shares ~12 aroma compounds · sharp green",   "~12 compounds"),
("surprising","soy_sauce","Enoki Mushroom"):("shares ~5 aroma compounds · delicate umami","~5 compounds"),
("surprising","soy_sauce","Bamboo Shoot"): ("shares ~5 aroma compounds · vegetal depth",  "~5 compounds"),
("surprising","soy_sauce","Sake"):         ("shares ~5 aroma compounds · fermented grain","~5 compounds"),
("surprising","soy_sauce","Bok Choy"):     ("shares ~5 aroma compounds · mild green",     "~5 compounds"),
("surprising","soy_sauce","Oyster Sauce"): ("shares ~5 aroma compounds · caramel umami",  "~5 compounds"),
# ── vinegar ──────────────────────────────────────────────────────────────────
("classic","vinegar","Soy Sauce"):        ("paired in ~1,800 recipes · acid-salt balance","~1,800 recipes"),
("classic","vinegar","Sesame Oil"):       ("paired in ~700 recipes · dressing foundation","~700 recipes"),
("classic","vinegar","Carrot"):           ("paired in ~250 recipes · pickled sweet",      "~250 recipes"),
("classic","vinegar","Tofu"):             ("paired in ~250 recipes · mapo depth",         "~250 recipes"),
("classic","vinegar","Light Soy Sauce"):  ("paired in ~250 recipes · Chinese pour",       "~250 recipes"),
("classic","vinegar","Salt"):             ("paired in ~250 recipes · brine base",         "~250 recipes"),
("surprising","vinegar","Scallion"):       ("shares ~12 aroma compounds · sharp green",   "~12 compounds"),
("surprising","vinegar","Wood Ear Mushroom"):("shares ~12 aroma compounds · black fungus","~12 compounds"),
("surprising","vinegar","Yard Long Bean"): ("shares ~8 aroma compounds · pickled vegetal","~8 compounds"),
("surprising","vinegar","Salt"):           ("shares ~8 aroma compounds · mineral acid",   "~8 compounds"),
("surprising","vinegar","Chili Oil"):      ("shares ~8 aroma compounds · Sichuan sour",   "~8 compounds"),
("surprising","vinegar","Oil"):            ("shares ~5 aroma compounds · emulsify base",  "~5 compounds"),
# ── tahini ───────────────────────────────────────────────────────────────────
("classic","tahini","Pomegranate Molasses"):("paired in ~1,800 recipes · Levantine sweet","~1,800 recipes"),
("classic","tahini","Sumac"):             ("paired in ~700 recipes · tart depth",         "~700 recipes"),
("classic","tahini","Chickpea"):          ("paired in ~700 recipes · hummus core",        "~700 recipes"),
("classic","tahini","Pastrami"):          ("paired in ~250 recipes · deli richness",      "~250 recipes"),
("classic","tahini","Bulgur"):            ("paired in ~250 recipes · grain bowl",         "~250 recipes"),
("classic","tahini","Labneh"):            ("paired in ~250 recipes · double cream",       "~250 recipes"),
("surprising","tahini","Labneh"):          ("shares ~12 aroma compounds · fermented fat",  "~12 compounds"),
("surprising","tahini","Zaatar"):          ("shares ~8 aroma compounds · herb sesame",    "~8 compounds"),
("surprising","tahini","Pumpkin Seed"):    ("shares ~5 aroma compounds · seed oil",       "~5 compounds"),
("surprising","tahini","Sumac"):           ("shares ~5 aroma compounds · tart sesame",    "~5 compounds"),
("surprising","tahini","Pomegranate Molasses"):("shares ~5 aroma compounds · fruity sesame","~5 compounds"),
("surprising","tahini","Brown Rice"):      ("shares ~5 aroma compounds · nutty bran",     "~5 compounds"),
# ── cinnamon ─────────────────────────────────────────────────────────────────
("classic","cinnamon","Vanilla"):         ("paired in ~1,800 recipes · warm baking",      "~1,800 recipes"),
("classic","cinnamon","Clove"):           ("paired in ~700 recipes · spice accord",       "~700 recipes"),
("classic","cinnamon","Nutmeg"):          ("paired in ~700 recipes · warm trio",          "~700 recipes"),
("classic","cinnamon","Apple"):           ("paired in ~250 recipes · apple pie",          "~250 recipes"),
("classic","cinnamon","Raisin"):          ("paired in ~250 recipes · spiced fruit",       "~250 recipes"),
("classic","cinnamon","Cardamom"):        ("paired in ~250 recipes · chai family",        "~250 recipes"),
("surprising","cinnamon","Clove"):         ("shares ~12 aroma compounds · eugenol twins",  "~12 compounds"),
("surprising","cinnamon","Nutmeg"):        ("shares ~8 aroma compounds · warm phenolic",  "~8 compounds"),
("surprising","cinnamon","Allspice"):      ("shares ~5 aroma compounds · spice family",   "~5 compounds"),
("surprising","cinnamon","Fennel Seed"):   ("shares ~5 aroma compounds · anise-warm",     "~5 compounds"),
("surprising","cinnamon","Fennel"):        ("shares ~5 aroma compounds · licorice bridge","~5 compounds"),
("surprising","cinnamon","Cardamom"):      ("shares ~5 aroma compounds · terpene family", "~5 compounds"),
# ── vanilla ──────────────────────────────────────────────────────────────────
("classic","vanilla","Cocoa Powder"):     ("paired in ~1,800 recipes · chocolate balance","~1,800 recipes"),
("classic","vanilla","Baking Powder"):    ("paired in ~700 recipes · cake base",          "~700 recipes"),
("classic","vanilla","Chocolate"):        ("paired in ~700 recipes · classic pairing",    "~700 recipes"),
("classic","vanilla","Milk Chocolate"):   ("paired in ~250 recipes · sweet cream",        "~250 recipes"),
("classic","vanilla","Cinnamon"):         ("paired in ~250 recipes · warm baking",        "~250 recipes"),
("classic","vanilla","White Chocolate"):  ("paired in ~250 recipes · pure sweet",         "~250 recipes"),
("surprising","vanilla","Chocolate"):      ("shares ~12 aroma compounds · vanillin overlap","~12 compounds"),
("surprising","vanilla","Cocoa Powder"):   ("shares ~5 aroma compounds · roasty vanillin","~5 compounds"),
("surprising","vanilla","Fudge"):          ("shares ~5 aroma compounds · cooked sugar",   "~5 compounds"),
("surprising","vanilla","Baking Soda"):    ("shares ~5 aroma compounds · alkaline sweet", "~5 compounds"),
("surprising","vanilla","Frosting"):       ("shares ~5 aroma compounds · sweet fat",      "~5 compounds"),
("surprising","vanilla","Hazelnut"):       ("shares ~5 aroma compounds · praline roast",  "~5 compounds"),
# ── black_pepper ─────────────────────────────────────────────────────────────
("classic","black_pepper","Paprika"):     ("paired in ~1,800 recipes · red spice duo",    "~1,800 recipes"),
("classic","black_pepper","Parsley"):     ("paired in ~700 recipes · seasoning herb",     "~700 recipes"),
("classic","black_pepper","Oregano"):     ("paired in ~250 recipes · Italian blend",      "~250 recipes"),
("classic","black_pepper","Salt"):        ("paired in ~250 recipes · universal pair",     "~250 recipes"),
("classic","black_pepper","Garlic"):      ("paired in ~250 recipes · pungent trio",       "~250 recipes"),
("classic","black_pepper","Shallot"):     ("paired in ~250 recipes · sharp allium",       "~250 recipes"),
("surprising","black_pepper","Marjoram"):  ("shares ~12 aroma compounds · terpene kin",   "~12 compounds"),
("surprising","black_pepper","Oregano"):   ("shares ~8 aroma compounds · carvacrol family","~8 compounds"),
("surprising","black_pepper","Nutmeg"):    ("shares ~8 aroma compounds · warm alkaloid",  "~8 compounds"),
("surprising","black_pepper","Parsley"):   ("shares ~8 aroma compounds · green pungent",  "~8 compounds"),
("surprising","black_pepper","Cumin"):     ("shares ~5 aroma compounds · warm phenol",    "~5 compounds"),
("surprising","black_pepper","Bay Leaf"):  ("shares ~5 aroma compounds · slow heat",      "~5 compounds"),
# ── turmeric ─────────────────────────────────────────────────────────────────
("classic","turmeric","Garam Masala"):    ("paired in ~1,800 recipes · Indian base",      "~1,800 recipes"),
("classic","turmeric","Mustard Seed"):    ("paired in ~700 recipes · warm spice",         "~700 recipes"),
("classic","turmeric","Lentil"):          ("paired in ~700 recipes · dal foundation",     "~700 recipes"),
("classic","turmeric","Salt"):            ("paired in ~250 recipes · spice bloom",        "~250 recipes"),
("classic","turmeric","Coconut Milk"):    ("paired in ~250 recipes · golden curry",       "~250 recipes"),
("classic","turmeric","Chili Pepper"):    ("paired in ~250 recipes · heat balance",       "~250 recipes"),
("surprising","turmeric","Cumin"):         ("shares ~12 aroma compounds · curcumin family","~12 compounds"),
("surprising","turmeric","Saffron"):       ("shares ~12 aroma compounds · golden pigment","~12 compounds"),
("surprising","turmeric","Curry Leaf"):    ("shares ~8 aroma compounds · terpenoid bond", "~8 compounds"),
("surprising","turmeric","Lemongrass"):    ("shares ~8 aroma compounds · citrus-earth",   "~8 compounds"),
("surprising","turmeric","Cardamom"):      ("shares ~5 aroma compounds · warm terpene",   "~5 compounds"),
("surprising","turmeric","Urad Dal"):      ("shares ~5 aroma compounds · earthy legume",  "~5 compounds"),
# ── beer ─────────────────────────────────────────────────────────────────────
("classic","beer","Horseradish"):         ("paired in ~1,800 recipes · bitter heat",      "~1,800 recipes"),
("classic","beer","Doubanjiang"):         ("paired in ~700 recipes · fermented umami",    "~700 recipes"),
("classic","beer","Coriander"):           ("paired in ~700 recipes · beer bread seed",    "~700 recipes"),
("classic","beer","Garlic"):              ("paired in ~250 recipes · pub anchor",         "~250 recipes"),
("classic","beer","Onion"):               ("paired in ~250 recipes · batter base",        "~250 recipes"),
("classic","beer","Leek"):                ("paired in ~250 recipes · allium lift",        "~250 recipes"),
("surprising","beer","Puffer Fish"):       ("shares ~12 aroma compounds · marine ferment", "~12 compounds"),
("surprising","beer","Doubanjiang"):       ("shares ~12 aroma compounds · fermented grain","~12 compounds"),
("surprising","beer","Pickled Ginger"):    ("shares ~8 aroma compounds · lactic acid",    "~8 compounds"),
("surprising","beer","Duck"):              ("shares ~8 aroma compounds · fatty Maillard",  "~8 compounds"),
("surprising","beer","Light Soy Sauce"):   ("shares ~5 aroma compounds · fermented salt",  "~5 compounds"),
("surprising","beer","Fermented Black Bean"):("shares ~5 aroma compounds · fermented depth","~5 compounds"),
}

def main():
    with open(PATH) as f:
        data = json.load(f)

    patched = 0
    missing = []

    for seed, seed_data in data["flavors"].items():
        for lens in ("classic", "surprising"):
            for match in seed_data[lens]:
                key = (lens, seed, match["name"])
                if key in COPY:
                    why, note = COPY[key]
                    match["why"]  = why
                    match["note"] = note
                    patched += 1
                else:
                    missing.append(key)

    with open(PATH, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)

    print(f"✓ Patched {patched} / {patched + len(missing)} pairings")
    if missing:
        print(f"  Missing ({len(missing)}):")
        for m in missing:
            print(f"    {m}")

if __name__ == "__main__":
    main()
